from pathlib import Path
start = """  const s4Info = technology.scoreModel.S4;\n  if (s4Info) {\n    const s4Card = createElement('section', { className: 'glass-card s4-card' });\n    s4Card.innerHTML = '<h3>S4 行业适配分细则</h3>';\n    const bucketList = createElement('ul');\n    (s4Info.prosperity?.buckets || []).forEach((bucket) => {\n      bucketList.appendChild(createElement('li', { text: `${bucket.label}：${bucket.score} 分` }));\n    });\n    s4Card.appendChild(createElement('h4', { text: '行业景气度分档' }));\n    s4Card.appendChild(bucketList);\n    const policyList = createElement('ul');\n    policyList.appendChild(createElement('li', { text: `基础分：${s4Info.policySupport.base} 分` }));\n    policyList.appendChild(createElement('li', { text: `加分上限：${s4Info.policySupport.addonsCap} 分（总分封顶 ${s4Info.policySupport.cap} 分）` }));\n    (s4Info.policySupport.addons || []).forEach((addon) => {\n      policyList.appendChild(createElement('li', { text: `${addon.label}：${addon.score} 分` }));\n    });\n    s4Card.appendChild(createElement('h4', { text: '政策扶持加分' }));\n    s4Card.appendChild(policyList);\n    panel.appendChild(s4Card);\n  }\n"""
replacement = """  const s4Info = technology.scoreModel.S4;\n  if (s4Info) {\n    const s4Card = createElement('section', { className: 'glass-card s4-card' });\n    s4Card.innerHTML = '<h3>S4 行业适配分细则</h3>';\n    const s4Grid = createElement('div', { className: 's4-grid' });\n\n    const leftCol = createElement('div', { className: 's4-column' });\n    leftCol.appendChild(createElement('h4', { text: '行业景气度分档' }));\n    const bucketList = createElement('ul');\n    (s4Info.prosperity?.buckets || []).forEach((bucket) => {\n      bucketList.appendChild(createElement('li', { text: `${bucket.label}：${bucket.score} 分` }));\n    });\n    leftCol.appendChild(bucketList);\n\n    const rightCol = createElement('div', { className: 's4-column' });\n    const policy = s4Info.policySupport || { base: 0, addons: [], addonsCap: 0, cap: 0 };\n    const policyTitle = `政策扶持加分（基础 ${policy.base || 0} 分，加分上限 ${policy.addonsCap || 0} 分）`;\n    rightCol.appendChild(createElement('h4', { text: policyTitle }));\n    const policyList = createElement('ul');\n    (policy.addons || []).forEach((addon) => {\n      policyList.appendChild(createElement('li', { text: `${addon.label}：${addon.score} 分` }));\n    });\n    rightCol.appendChild(policyList);\n    rightCol.appendChild(createElement('p', { className: 'metric-caption', text: `加分封顶：${policy.cap or (policy.base or 0) + (policy.addonsCap or 0)} 分` }));\n\n    s4Grid.append(leftCol, rightCol);\n    s4Card.appendChild(s4Grid);\n    panel.appendChild(s4Card);\n  }\n"""
path = Path('assets/js/app.js')
text = path.read_text(encoding='utf-8')
if start not in text:
    raise SystemExit('Original S4 block not matched')
text = text.replace(start, replacement)
path.write_text(text, encoding='utf-8')
